### ISSUE TITLE
バックエンドの起動に必要なPythonパッケージを記載してください

### ISSUE THREAD

**Issue by yhiraki** [NagaoTadashi/football-matching-app#1]
最も一般的でよく使われる方法は、 `requirements.txt` を設置する方法です。

https://pip.pypa.io/en/stable/user_guide/#requirements-files

---

例えば、次のような形式で `requirements.txt` を設置します。

```txt
Django==5.1
djangorestframework==3.15.2
```

ユーザーは次の方法で必要なパッケージの一覧をインストールできます。

```sh
pip install -r requirements.txt
```

**Comment by NagaoTadashi** [comment]
backendディレクトリ直下にrequirements.txtを追加しました。
